-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-11-30 21:30:52 EET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE categorie 
    ( 
     denumire     VARCHAR2 (15)  NOT NULL , 
     id_categorie NUMBER (2)  NOT NULL , 
     id_parinte   NUMBER (2) 
    ) 
    LOGGING 
;

ALTER TABLE categorie 
    ADD CONSTRAINT categorie_denumire_ck 
    CHECK (( LENGTH(denumire)>=3 AND REGEXP_LIKE(denumire, '^[A-Za-z]+$') )) 
;

ALTER TABLE categorie 
    ADD CONSTRAINT categorie_PK PRIMARY KEY ( id_categorie ) ;

CREATE TABLE comanda 
    ( 
     id_comanda               NUMBER (9)  NOT NULL , 
     status                   VARCHAR2 (20) DEFAULT 'plasat'  NOT NULL , 
     pret_transport           NUMBER (2) DEFAULT 25  NOT NULL , 
     data_plasarii            DATE DEFAULT SYSDATE  NOT NULL , 
     status_plata             VARCHAR2 (10) DEFAULT 'efectuat'  NOT NULL , 
     data_livrare             DATE , 
     id_produs                NUMBER (9)  NOT NULL , 
     id_utilizator_cumparator NUMBER (7)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE comanda 
    ADD CONSTRAINT comanda_status_ck 
    CHECK (status IN ('anulat', 'confirmat', 'expediat', 'in_curs_de_retur', 'livrat', 'plasat', 'returnat')) 
;

ALTER TABLE comanda 
    ADD CONSTRAINT comanda_pret_transport_ck 
    CHECK (pret_transport IN (25, 50)) 
;

ALTER TABLE comanda 
    ADD CONSTRAINT comanda_status_plata_ck 
    CHECK (status_plata IN ('efectuat', 'finalizat', 'restituit')) 
;

ALTER TABLE comanda 
    ADD CONSTRAINT comanda_data_livrare 
    CHECK ((data_livrare IS NULL OR data_livrare > data_plasarii)) 
;
CREATE UNIQUE INDEX comanda__IDX ON comanda 
    ( 
     id_produs ASC 
    ) 
    LOGGING 
;

ALTER TABLE comanda 
    ADD CONSTRAINT comanda_PK PRIMARY KEY ( id_comanda ) ;

CREATE TABLE feedback 
    ( 
     id_feedback            NUMBER (10)  NOT NULL , 
     nota                   NUMBER (2,1)  NOT NULL , 
     justificare            VARCHAR2 (500) , 
     id_comanda             NUMBER (9)  NOT NULL , 
     id_utilizator_creator  NUMBER (7)  NOT NULL , 
     id_utilizator_primitor NUMBER (7)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE feedback 
    ADD CONSTRAINT feedback_nota_ck 
    CHECK (nota BETWEEN 0 AND 5) 
;

ALTER TABLE feedback 
    ADD CONSTRAINT feedback_PK PRIMARY KEY ( id_feedback ) ;

CREATE TABLE istoric_pret 
    ( 
     data_inregistrare DATE DEFAULT SYSDATE  NOT NULL , 
     pret              NUMBER (6,2)  NOT NULL , 
     id_produs         NUMBER (9)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE istoric_pret 
    ADD CONSTRAINT istoric_pret_pret_ck 
    CHECK (pret BETWEEN 0 AND 2000) 
;

ALTER TABLE istoric_pret 
    ADD CONSTRAINT istoric_pret_PK PRIMARY KEY ( id_produs, data_inregistrare ) ;

CREATE TABLE mesaj 
    ( 
     id_mesaj               NUMBER (15)  NOT NULL , 
     continut               VARCHAR2 (500)  NOT NULL , 
     ora                    DATE DEFAULT SYSDATE  NOT NULL , 
     id_utilizator_primeste NUMBER (7)  NOT NULL , 
     id_utilizator_trimite  NUMBER (7)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE mesaj 
    ADD CONSTRAINT mesaj_PK PRIMARY KEY ( id_mesaj ) ;

CREATE TABLE produs 
    ( 
     id_produs              NUMBER (9)  NOT NULL , 
     titlu_produs           VARCHAR2 (50)  NOT NULL , 
     descriere              VARCHAR2 (300) , 
     stare                  VARCHAR2 (15) DEFAULT 'acceptabila' , 
     status                 VARCHAR2 (10) DEFAULT 'activ'  NOT NULL , 
     id_categorie           NUMBER (2)  NOT NULL , 
     id_utilizator_vanzator NUMBER (7)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE produs 
    ADD CONSTRAINT produs_titlu_produs_ck 
    CHECK (LENGTH(titlu_produs)>=5) 
;

ALTER TABLE produs 
    ADD CONSTRAINT produs_stare_ck 
    CHECK (stare IN ('acceptabila', 'buna', 'foarte_buna', 'nou', 'rea')) 
;

ALTER TABLE produs 
    ADD CONSTRAINT produs_status_ck 
    CHECK (status IN ('activ', 'inactiv')) 
;

ALTER TABLE produs 
    ADD CONSTRAINT produs_PK PRIMARY KEY ( id_produs ) ;

CREATE TABLE utilizator 
    ( 
     id_utilizator    NUMBER (7)  NOT NULL , 
     nume_utilizator  VARCHAR2 (50)  NOT NULL , 
     tara             VARCHAR2 (15) DEFAULT 'romania'  NOT NULL , 
     parola           VARCHAR2 (30)  NOT NULL , 
     data_creare_cont DATE DEFAULT SYSDATE  NOT NULL , 
     data_nasterii    DATE  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE utilizator 
    ADD CONSTRAINT utilizator_nume_utilizator_ck 
    CHECK (( LENGTH(nume_utilizator)>=5 AND nume_utilizator NOT LIKE '% %'  AND TRIM(nume_utilizator) = nume_utilizator)) 
;

ALTER TABLE utilizator 
    ADD CONSTRAINT utilizator_tara_ck 
    CHECK (tara IN ('austria', 'bulgaria', 'franta', 'germania', 'grecia', 'italia', 'polonia', 'romania', 'serbia', 'slovacia', 'slovenia', 'spania', 'ungaria')) 
;

ALTER TABLE utilizator 
    ADD CONSTRAINT utilizator_parola_ck 
    CHECK (LENGTH(parola)>=8) 
;

ALTER TABLE utilizator 
    ADD CONSTRAINT utilizator_PK PRIMARY KEY ( id_utilizator ) ;

ALTER TABLE utilizator 
    ADD CONSTRAINT nume_utilizator_uk UNIQUE ( nume_utilizator ) ;

ALTER TABLE produs 
    ADD CONSTRAINT categorie_produs_fk FOREIGN KEY 
    ( 
     id_categorie
    ) 
    REFERENCES categorie 
    ( 
     id_categorie
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE categorie 
    ADD CONSTRAINT categorie_subcategorie_fk FOREIGN KEY 
    ( 
     id_parinte
    ) 
    REFERENCES categorie 
    ( 
     id_categorie
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE feedback 
    ADD CONSTRAINT comanda_feedback_fk FOREIGN KEY 
    ( 
     id_comanda
    ) 
    REFERENCES comanda 
    ( 
     id_comanda
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE comanda 
    ADD CONSTRAINT produs_comanda_fk FOREIGN KEY 
    ( 
     id_produs
    ) 
    REFERENCES produs 
    ( 
     id_produs
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE istoric_pret 
    ADD CONSTRAINT produs_istoric_pret_fk FOREIGN KEY 
    ( 
     id_produs
    ) 
    REFERENCES produs 
    ( 
     id_produs
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE comanda 
    ADD CONSTRAINT utilizator_comanda_fk FOREIGN KEY 
    ( 
     id_utilizator_cumparator
    ) 
    REFERENCES utilizator 
    ( 
     id_utilizator
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE feedback 
    ADD CONSTRAINT utilizator_feedback_creat_fk FOREIGN KEY 
    ( 
     id_utilizator_creator
    ) 
    REFERENCES utilizator 
    ( 
     id_utilizator
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE feedback 
    ADD CONSTRAINT utilizator_feedback_primit_fk FOREIGN KEY 
    ( 
     id_utilizator_primitor
    ) 
    REFERENCES utilizator 
    ( 
     id_utilizator
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE mesaj 
    ADD CONSTRAINT utilizator_mesaj_primit_fk FOREIGN KEY 
    ( 
     id_utilizator_primeste
    ) 
    REFERENCES utilizator 
    ( 
     id_utilizator
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE mesaj 
    ADD CONSTRAINT utilizator_mesaj_trimis_fk FOREIGN KEY 
    ( 
     id_utilizator_trimite
    ) 
    REFERENCES utilizator 
    ( 
     id_utilizator
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE produs 
    ADD CONSTRAINT utilizator_produs_fk FOREIGN KEY 
    ( 
     id_utilizator_vanzator
    ) 
    REFERENCES utilizator 
    ( 
     id_utilizator
    ) 
    NOT DEFERRABLE 
;

CREATE OR REPLACE TRIGGER comanda_data_plasarii_no_update_trg 
    BEFORE UPDATE ON comanda 
    FOR EACH ROW 
BEGIN
	IF :NEW.data_plasarii <> :OLD.data_plasarii THEN
		RAISE_APPLICATION_ERROR(-20001,'Data de plasare a comenzii nu poate fi schimbata');
	END IF;
END; 
/

CREATE OR REPLACE TRIGGER istoric_pret_data_inregistrare_no_update_trg 
    BEFORE UPDATE ON istoric_pret 
    FOR EACH ROW 
BEGIN
	IF :NEW.data_inregistrare <> :OLD.data_inregistrare THEN
		RAISE_APPLICATION_ERROR(-20001,'Data de setare a pretului nu poate fi schimbata');
	END IF;
END; 
/

CREATE OR REPLACE TRIGGER mesaj_ora_no_update_trg 
    BEFORE UPDATE ON mesaj 
    FOR EACH ROW 
BEGIN
	IF :NEW.ora <> :OLD.ora THEN
		RAISE_APPLICATION_ERROR(-20001,'Momentul de creare al mesajului nu poate fi schimbat');
	END IF;
END; 
/

CREATE OR REPLACE TRIGGER produs_inactiv_dupa_comanda_trg 
    AFTER INSERT ON comanda 
    FOR EACH ROW 
BEGIN
    UPDATE produs
    SET status = 'inactiv'
    WHERE id_produs = :NEW.id_produs;
END; 
/

CREATE OR REPLACE TRIGGER trg_utilizator_data_nasterii_trg 
    BEFORE INSERT OR UPDATE ON utilizator 
    FOR EACH ROW 
BEGIN
	IF(( :new.data_nasterii > ADD_MONTHS(SYSDATE, -18*12) OR :new.data_nasterii < ADD_MONTHS(SYSDATE, -100*12 ) ))
	THEN
		RAISE_APPLICATION_ERROR(-20001,'Data nasterii invalida' || TO_CHAR(:new.data_nasterii,'DD:MM:YYYY') || ' utilizatorul trebuie sa aiba varsta peste 18 ani si sub 100 de ani');
	END IF;
END; 
/

CREATE OR REPLACE TRIGGER utilizator_data_creare_no_update_trg 
    BEFORE UPDATE ON utilizator 
    FOR EACH ROW 
BEGIN
	IF :NEW.data_creare_cont <> :OLD.data_creare_cont THEN
		RAISE_APPLICATION_ERROR(-20001,'Data de creare a contului nu poate fi schimbata');
	END IF;
END; 
/

CREATE SEQUENCE categorie_id_categorie_seq 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER categorie_id_categorie_trg 
BEFORE INSERT ON categorie 
FOR EACH ROW 
WHEN (NEW.id_categorie IS NULL) 
BEGIN 
    :NEW.id_categorie := categorie_id_categorie_seq.NEXTVAL; 
END;
/

CREATE SEQUENCE comanda_id_comanda_seq 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER comanda_id_comanda_trg 
BEFORE INSERT ON comanda 
FOR EACH ROW 
WHEN (NEW.id_comanda IS NULL) 
BEGIN 
    :NEW.id_comanda := comanda_id_comanda_seq.NEXTVAL; 
END;
/

CREATE SEQUENCE feedback_id_feedback_seq 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER feedback_id_feedback_trg 
BEFORE INSERT ON feedback 
FOR EACH ROW 
WHEN (NEW.id_feedback IS NULL) 
BEGIN 
    :NEW.id_feedback := feedback_id_feedback_seq.NEXTVAL; 
END;
/

CREATE SEQUENCE mesaj_id_mesaj_seq 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER mesaj_id_mesaj_trg 
BEFORE INSERT ON mesaj 
FOR EACH ROW 
WHEN (NEW.id_mesaj IS NULL) 
BEGIN 
    :NEW.id_mesaj := mesaj_id_mesaj_seq.NEXTVAL; 
END;
/

CREATE SEQUENCE produs_id_produs_seq 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER produs_id_produs_trg 
BEFORE INSERT ON produs 
FOR EACH ROW 
WHEN (NEW.id_produs IS NULL) 
BEGIN 
    :NEW.id_produs := produs_id_produs_seq.NEXTVAL; 
END;
/

CREATE SEQUENCE utilizator_id_utilizator_seq 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER utilizator_id_utilizator_trg 
BEFORE INSERT ON utilizator 
FOR EACH ROW 
WHEN (NEW.id_utilizator IS NULL) 
BEGIN 
    :NEW.id_utilizator := utilizator_id_utilizator_seq.NEXTVAL; 
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             1
-- ALTER TABLE                             32
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                          12
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          6
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
